name: Build and push Docker images

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

env:
  CONTAINER_NAME: node-devcontainer

jobs:
  build-and-push-docker-images:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - dockerfile: src/Dockerfile.node-18-slim.dev
            containerTag: 18-slim.0.0
          - dockerfile: src/Dockerfile.node-17-slim.dev
            containerTag: 17-slim.0.0
          - dockerfile: src/Dockerfile.node-16-slim.dev
            containerTag: 16-slim.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ env.CONTAINER_NAME }}:${{ matrix.images.containerTag }}
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ matrix.images.containerTag }}
          file: ${{ matrix.images.dockerfile }}
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          build-args: |
            ROOT_PASS=${{ secrets.DOCKER_IMAGE_ROOT_PASS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Set Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}
          short-description: NodeJS devcontainers
          readme-filepath: src/DOCKER_README.md

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
